import Head from 'next/head'

export default function AppHead() {
    return (
        <Head>
            <title>Olas Paste Bin</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}
